ARG BASE_IMAGE=stevendargaville/petsc_64_bit

FROM ${BASE_IMAGE}
# Use the optimised petsc build by default
ARG ARCH=arch-linux-c-opt

LABEL maintainer="Steven Dargaville"
LABEL description="PFLARE_64_bit"

ENV PETSC_ARCH=$ARCH
# Ensure any test failures are caught and the build fails
ENV PETSC_OPTIONS="-on_error_abort"

WORKDIR /build

COPY . /build/PFLARE

# Build and test PFLARE
RUN set -e; \
    cd PFLARE && \
    make -j2 && make python && make -j2 check && make -j2 tests

WORKDIR /build/PFLARE
