ARG BASE_IMAGE=stevendargaville/petsc_intel

FROM ${BASE_IMAGE}
# Checkout the main branch by default
ARG BRANCH=main
ARG ARCH=arch-linux-intel

LABEL maintainer="Steven Dargaville"
LABEL description="PFLARE_intel"

ENV CHECKOUT_BRANCH=$BRANCH
ENV PETSC_ARCH=$ARCH
# Ensure any test failures are caught and the build fails
ENV PETSC_OPTIONS="-on_error_abort"

WORKDIR /build

# Clone PFLARE and run all the tests
# Only run the serial tests until we figure out what is breaking the 
# power basis in parallel (it looks like the Intel MPI rather than the compilers)
RUN source /opt/intel/oneapi/setvars.sh && \
    set -e; \
    echo "Cloning branch: ${CHECKOUT_BRANCH}" && \
    git clone --branch ${CHECKOUT_BRANCH} https://github.com/PFLAREProject/PFLARE.git && \
    cd PFLARE && \
    make -j2 && make -j2 check && \
    make -j2 tests_short_serial && make -j2 tests_medium_serial

WORKDIR /build/PFLARE
